name: geospatial

channels:
 - conda-forge
 - pytorch
 - nvidia
 - defaults

dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - jupyterlab
  - matplotlib
  - jupyter
  - nb_conda
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - tensorflow-gpu
  - scikit-learn
  - seaborn
  - plotly
  - ipywidgets
